#!/bin/sh
#
# Start the QEMU network....
#

case "$1" in
  start)
	/sbin/modprobe cdc_ether
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
